// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "TiltMaze",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "TiltMaze",
            targets: ["AppModule"],
            bundleIdentifier: "com.student.TiltMaze",
            teamIdentifier: "27XDPXJJ23",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .motion(purposeString: "Controls the gravity of the maze using the device tilt."),
                .camera(purposeString: "Allows face tracking for head control mode.")
            ],
            appCategory: .games
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
